### PR TITLE
Fix parsing on saving through query

### LINKED ISSUE #42: model.refresh is not working properly | bug
When I call model.refresh() I will get next exception:

```
SyntaxError: Unexpected token o in JSON at position 1
    at Object.parse (native)
    at constructor.jsonColumns.forEach.column (/Users/seeden/Documents/git/goodmodule.com/node_modules/bookshelf-json-columns/dist/index.js:38:38)
    at Array.forEach (native)
    at Quiz.parse (/Users/seeden/Documents/git/goodmodule.com/node_modules/bookshelf-json-columns/dist/index.js:36:32)
    at /Users/seeden/Documents/git/goodmodule.com/node_modules/bookshelf/lib/base/events.js:176:25
From previous event:
    at Quiz.triggerThen (/Users/seeden/Documents/git/goodmodule.com/node_modules/bookshelf/lib/base/events.js:175:32)
    at Quiz.<anonymous> (/Users/seeden/Documents/git/goodmodule.com/node_modules/bookshelf/lib/model.js:702:19)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
From previous event:
    at Quiz.<anonymous> (/Users/seeden/Documents/git/goodmodule.com/node_modules/bookshelf/lib/model.js:685:8)
From previous event:
    at Quiz.refresh (/Users/seeden/Documents/git/goodmodule.com/node_modules/bookshelf/lib/model.js:567:17)
```

Instead of this everything else working fine.

bookshelf-json-columns@2.0.0 with sqllite

### PR DESCRIPTION
**Pull request by ricardogama**
This PR fixes parsing of columns when a `fetched` event is triggered after inserting or updating through knex query builder.

Closes #42

### CODE REVIEW

File: test/sqlite/index.js [hunk 1]
```diff
@@ -173,6 +181,24 @@ describe('with SQLite client', () => {
...
 
+    it('should keep a JSON value on fetch', async () => {
+      const model = await Model.forge().save({ foo: ['bar'] });
+
+      await model.refresh();
+
+      model.get('foo').should.eql(['bar']);
+    });
+
+    it('should keep a JSON value updating through query', async () => {
```
Comment (abelsoares) [inline test/sqlite/index.js]: `should keep a JSON value when updating through query`
